name: 'Nightly Data Update'
on:
  workflow_dispatch:
  schedule:
    - cron: '00 9 * * *' # once a day at 9:00 AM UTC / 4:00 AM EST
  
jobs:
  # A helpful guide on installing poetry in Github Actions can be found here:
  # https://jacobian.org/til/github-actions-poetry/
  
  # Load all the blue banners that have been won since the current year.
  load_blue_banners:
    name: Load Blue Banners
    timeout-minutes: 30
    uses: ./.github/run_python.yaml
    secrets: inherit
    with:
      run_command: python main.py banner --banner_mode=since_current_year
    

  # Load all the events and update their data.
  load_event_data:
    name: Load Event Data
    needs: [load_blue_banners]
    timeout-minutes: 30
    uses: ./.github/run_python.yaml
    secrets: inherit
    with:
      run_command: python main.py event --event_mode=since_current_year
    
  
  # Refresh the team information in case it has changed. Also update the team data.
  load_team_data:
    name: Load Team Data
    needs: [load_blue_banners]
    timeout-minutes: 30
    uses: ./.github/run_python.yaml
    secrets: inherit
    with:
      run_command: python main.py team --team_mode=full
